version: 1.0.{build}
init:
- cmd: >-
    PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

    echo %PATH%

    python --version

    pip --version
environment:
  PYTHON: C:\Python34
install:
- cmd: >-
    pip install py2exe

    pip install -r requirements.txt
build_script:
- cmd: >-
    python setup.py py2exe
    
    7z a Wangview.zip dist
artifacts:
- path: Wangview.zip
  name: Wangview executable package
