version: 1.0.{build}
init:
- cmd: >-
    PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

    echo %PATH%

    python --version

    pip --version
environment:
  PYTHON: C:\Python35
install:
- cmd: >-
    pip install PyInstaller

    pyinstaller --version

    pip install -r requirements.txt
build_script:
- cmd: >-
    pyinstaller Wangview.py -D -c --add-bin %PYTHON%\Lib\site-packages\bearlibterminal\BearLibTerminal.dll;. --hidden-import pythoncom --exclude-module numpy --exclude-module scipy --exclude-module pandas --exclude-module IPython --exclude-module matplotlib --exclude-module PyQt --exclude-module PyQt5 --exclude-module PIL --exclude-module setuptools --exclude-module dist-utils --exclude-module sqlite3  --exclude-module jinja2 --exclude-module lib2to3 --exclude-module cryptography --exclude-module pygments --exclude-module requests --exclude-module PyQt5.QtGui --exclude-module tkinter --exclude-module jsonschema --exclude-module gevent --exclude-module multiprocessing --exclude-module decimal --exclude-module lzma --exclude-module tornado --exclude-module zmq --exclude-module ssl --exclude-module overlapped --exclude-module email --exclude-module socket

    7z a Wangview.zip dist/*
artifacts:
- path: Wangview.zip
  name: Wangview executable package
